/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.*;
import view.View;

/**
 *
 * @author Quecheri
 * @version 1.1
 */
public class Window extends javax.swing.JFrame {
    View view;
    Model mod;
    /**
     * Creates new form Window
     */
    view.TableModel tabmodel=new TableModel();
    /**
     * Inicjalize Form Window
     * @param mod from controler
     * @param view from controler
     */
    public Window(Model mod, View view) {
        initComponents();
        this.mod=mod;
        this.view=view;
    }

   
    /**
     * 
     * @return a number provided by user
     */
    public String getNumber()
    {
        return inputNumberFiled.getText();
    }
    /**
     * 
     * Sets  result string on screen
     */
    public void setResult(String text)
    {
        resultText.setText(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoLabel = new javax.swing.JLabel();
        RecalculateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inputNumberFiled = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resultText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Possible characters");
        setBackground(new java.awt.Color(255, 204, 102));

        InfoLabel.setText("Enter a number within correct boundry");

        RecalculateBtn.setText("Change");
        RecalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecalculateBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Number:");

        inputNumberFiled.setText("X");
        inputNumberFiled.setBorder(new javax.swing.border.MatteBorder(null));
        inputNumberFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumberFiledActionPerformed(evt);
            }
        });

        jLabel3.setText("Result:");

        resultText.setText("10");

        jTable1.setBackground(new java.awt.Color(200, 255, 200));
        jTable1.setModel(tabmodel);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(InfoLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNumberFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(resultText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RecalculateBtn))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputNumberFiled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resultText)
                    .addComponent(RecalculateBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Sends recived string and sets result or provide a message
 * @param evt s
 */
    private void RecalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecalculateBtnActionPerformed
       mod.setNumber(getNumber());
        if(mod.isRomanNumber())
           {
                //view.showMessageBox("You have provided roman number");
                InfoLabel.setText("You have provided roman number");
                mod.changeToArabic();
           }
           else if(mod.isArabicNumber())
           {
               //view.showMessageBox("You have provided arabic number");
               InfoLabel.setText("You have provided arabic number");
               try
               {
                    mod.changeToRoman();
               }
               catch (model.NumberOutOfBoundsExeption ex)
               {
                   view.printErrorMessage(ex.getMessage());
                   //error=true;
               }
               catch (NumberFormatException ex)
               {
                   view.printErrorMessage("Number wasn't an integer");  
                   
               }
           }
        else
           {
               InfoLabel.setText("You have provided neither roman nor arabic number");
           }
       resultText.setText(mod.getConvertedNumber());
    }//GEN-LAST:event_RecalculateBtnActionPerformed

    private void inputNumberFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumberFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumberFiledActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JButton RecalculateBtn;
    private javax.swing.JTextField inputNumberFiled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel resultText;
    // End of variables declaration//GEN-END:variables
}
